version: "3.7"
networks:
  journal_service_network:
    name: journal_service_network
services:
  nginx:
    container_name: journal_service_nginx
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - "80:8081"
      - "443:443"
      - "9082:9082"
    depends_on:
      - php-fpm
      - node
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./../:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - journal_service_network
  php-fpm:
    container_name: journal_service
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    image: journal_service/php-fpm
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./../:/var/www/html
    networks:
      - journal_service_network
  node:
#    command: tail -F anything
    image: journal_service/node
    user: "node"
    build:
      context: ./node/
      dockerfile: Dockerfile
    container_name: journal_service_node
    volumes:
      - ./../frontend:/var/www/html/frontend
    ports:
      - "5174:5174"
    networks:
      - journal_service_network
  mysql:
    container_name: journal_service_mysql
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - journal_service_network
#  phpmyadmin:
#    image: phpmyadmin:fpm-alpine
#    container_name: journal_service_phpmyadmin
#    ports:
#      - "8082:80"
#    env_file:
#      - .env
#    depends_on:
#      - mysql
#    networks:
#      - journal_service_network
